import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'
import Link from 'next/link'
 
const fetcher = (...args) => fetch(...args).then((res) => res.json())

export default function Home() {

  const { data, error } = useSWR('https://dummyjson.com/products', fetcher);
  console.log(data)

  if(error){
    return <h3>An Error Occured</h3>
  }
  
  if(!data){
    return <h3>Loading</h3>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>My Next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.list}>
        {
          data?.products.map((item)=><Link key={item.id} href={`/products/${item.id}`}><li>{item.title}</li></Link>)
        }
      </div>
    </div>
  )
}
